version: '3'
services:
  gkbot:
    build: .
    image: gkbot
    tty: True
    volumes:
      - gkbot_data:/data
      - $HOME/.cache/gkbot:/root/.cache/gkbot
      - ./services/bot-api/data:/var/lib/telegram-bot-api
    env_file: .env
    network_mode: bridge
    container_name: gkbot
volumes:
  gkbot_data:
  bot_api_data:
